---
abstract: 'Makes HTTP::Response objects stringable'
author:
  - 'Naveed Massjouni <naveed@vt.edu>'
build_requires:
  File::Spec: 0
  IO::Handle: 0
  IPC::Open3: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Response-Stringable
requires:
  Role::Tiny: 0
  overload: 0
resources:
  bugtracker: http://github.com/ironcamel/HTTP-Response-Stringable/issues
  repository: git://github.com/ironcamel/HTTP-Response-Stringable.git
version: 0.0002
